### ISSUE TITLE
new instance always starts green

### ISSUE THREAD

**Issue by maartenderie** [Rami-Wohl/shared-worker-lib-demo#1]
..and I HATE green

❤️ keep on dude

**Comment by Rami-Wohl** [comment]
Thanks a lot for reporting this bug, I don’t know how I could have overlooked this previously. I will consult an eye doctor and deploy a fix asap. Which color would you like to be set as default? 😄

**Comment by Rami-Wohl** [comment]
New instance now starts as _anything but green_
